"use strict";
const selected = new Set(new URLSearchParams(location.search).get("ids")?.split(",").filter(Boolean) || []);
const byId = id => document.getElementById(id);
const text = (tag, value, className) => { const node=document.createElement(tag); node.textContent=value; if(className) node.className=className; return node; };
const money = (value, currency) => value == null ? "Unavailable" : `${currency || ""} ${Number(value).toFixed(2)}`.trim();
function option(select, value){ select.append(text("option", value)); select.lastChild.value=value; }
function updateSelection(){ byId("compare-count").textContent=String(selected.size); byId("compare-link").href=`/compare.html?ids=${encodeURIComponent([...selected].join(","))}`; }
function card(product){ const article=text("article","","product-card"); article.append(text("div",product.category,"placeholder"),text("h3",product.display_name)); const meta=text("p",`${product.category} · ${product.native_mount}`); article.append(meta,text("p",`NEW ${money(product.new_median,product.market_currency)} · USED ${money(product.used_median,product.market_currency)}`)); const badges=text("p","","badges"); if(product.owned) badges.append(text("span","Owned")); if(product.wishlist) badges.append(text("span",`Wishlist ${product.wishlist_priority || ""}`)); article.append(badges); const actions=text("div","","actions"); const details=text("a","Details"); details.href=`/product.html?id=${encodeURIComponent(product.id)}`; const compare=text("button",selected.has(product.id)?"Remove":"Compare"); compare.type="button"; compare.addEventListener("click",()=>{ if(selected.has(product.id)) selected.delete(product.id); else if(selected.size<4) selected.add(product.id); else byId("message").textContent="A maximum of four products can be compared."; compare.textContent=selected.has(product.id)?"Remove":"Compare"; updateSelection(); }); actions.append(details,compare); article.append(actions); return article; }
async function load(){ const params=new URLSearchParams(); ["category","brand","mount","owned","wishlist","market","sort"].forEach(id=>{if(byId(id).value)params.set(id,byId(id).value)}); if(byId("confidence").value)params.set("confidence_min",byId("confidence").value); if(byId("search").value)params.set("q",byId("search").value); if(["newest","confidence"].includes(byId("sort").value))params.set("order","desc"); const response=await fetch(`/api/products?${params}`); const data=await response.json(); const grid=byId("products"); grid.replaceChildren(); if(!response.ok){byId("message").textContent=data.error.message;return;} byId("message").textContent=data.count?`${data.count} products`:"No products match your search."; data.products.forEach(product=>grid.append(card(product))); if(data.filters){ [["category",data.filters.categories],["brand",data.filters.brands],["mount",data.filters.mounts]].forEach(([id,values])=>{const select=byId(id); if(select.options.length===1)values.forEach(value=>option(select,value));});} }
async function context(){ const data=await (await fetch("/api/context")).json(); byId("wishlist-count").textContent=String(data.active_wishlist_count); byId("owned-count").textContent=String(data.owned_product_ids.length); byId("decision-count").textContent=String(data.recent_decision_count); }
byId("search-form").addEventListener("submit",event=>{event.preventDefault();load();}); document.querySelectorAll("select,input[type=number]").forEach(control=>control.addEventListener("change",load)); updateSelection(); load(); context();
